name: Regular Check

on:
  schedule:
    - cron: '*/4 * * * *'
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install
        run: pip3 install -r requirements.txt
      - name: run
        run: python3 ias.py